name: "Submit to Web Store"
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the Chrome extension
        run: pnpm build

      - name: Package the Chrome extension
        run: pnpm package

      - name: Build the Firefox extension
        run: pnpm build:firefox

      - name: Package the Firefox extension
        run: pnpm package:firefox

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          chrome-file: build/chrome-mv3-prod.zip
          firefox-file: build/firefox-mv2-prod.zip
